---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jasschallenge-service"
  namespace: "default"
  labels:
    app: "jasschallenge"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  selector:
    app: "jasschallenge"
  type: "ClusterIP"
