---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "cnnbot2"
  namespace: "default"
  labels:
    app: "cnnbot2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "cnnbot2"
  template:
    metadata:
      labels:
        app: "cnnbot2"
    spec:
      containers:
      - name: "cnnbot-sha256-1"
        image: "eu.gcr.io/modular-source-288719/cnnbot@sha256:b4c60b1454534c65068231e765c84bdaf1ace5a9f5d0e016e55c83008b3438d7"
        resources:
          requests:
            cpu: "200m"
        args: ["-n", "bot4", "-rl", "True", "-t", "1", "-m", "TRAIN", "-s", "ws://jasschallenge-service:3000"]