apiVersion: "v1"
kind: "Service"
metadata:
  name: "rulebot1-tb"
  namespace: "default"
  labels:
    app: "rulebot1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 6006
  selector:
    app: "rulebot1"
  type: "LoadBalancer"
  loadBalancerIP: ""
