---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rulebot2"
  namespace: "default"
  labels:
    app: "rulebot2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rulebot2"
  template:
    metadata:
      labels:
        app: "rulebot2"
    spec:
      containers:
      - name: "rulebot-sha256-1"
        image: "eu.gcr.io/modular-source-288719/rulebot@sha256:bc2a523f9ba388e664f9c3f9902fa1e001ee5fbbf58441a3815bb7af393c8ac6"
        resources:
          requests:
            cpu: "50m"
