apiVersion: "v1"
kind: "Service"
metadata:
  name: "relubot2-tb"
  namespace: "default"
  labels:
    app: "relubot2"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 6006
  selector:
    app: "relubot2"
  type: "LoadBalancer"
  loadBalancerIP: ""
